version: '3.4'

services:
  materialswarehouse:
    container_name: materialswarehouse
    ports:
        - 5000:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    build:
        context: .
        dockerfile: MaterialsWarehouse/MaterialsWarehouse.API/Dockerfile
