version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - 1433:1433
    volumes:
      - sqlserverdata:/var/opt/mssql 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Manufacturing2023
    networks: 
      - manufacturing-network
      
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    hostname: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'
    networks: 
      - manufacturing-network

  materialswarehouse:
    container_name: materialswarehouse
    ports:
        - 5000:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    build:
        context: .
        dockerfile: MaterialsWarehouse/MaterialsWarehouse.API/Dockerfile
    depends_on:
        - sqlserver
        - rabbitmq
    networks: 
      - manufacturing-network
      
  processingmachines:
    container_name: processingmachines
    ports:
        - 5001:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    build:
        context: .
        dockerfile: ProcessingMachines/ProcessingMachines.API/Dockerfile
    depends_on:
        - sqlserver
        - rabbitmq
    networks: 
      - manufacturing-network
      
  transportations:
    container_name: transportations
    ports:
        - 5002:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    build:
        context: .
        dockerfile: Transportations/Transportations.API/Dockerfile
    depends_on:
        - sqlserver
        - rabbitmq
    networks: 
      - manufacturing-network
      
  productswarehouse:
    container_name: productswarehouse
    ports:
        - 5003:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    build:
        context: .
        dockerfile: ProductsWarehouse/ProductsWarehouse.API/Dockerfile
    depends_on:
        - sqlserver
        - rabbitmq
    networks: 
      - manufacturing-network    
      
  workfloworchestrator:
    container_name: workfloworchestrator
    ports:
        - 5005:80
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    build:
        context: .
        dockerfile: WorkflowOrchestrator/WorkflowOrchestrator.API/Dockerfile
    depends_on:
        - sqlserver
        - rabbitmq
    networks: 
      - manufacturing-network

networks:
  manufacturing-network:

volumes:
  sqlserverdata:
    driver: local