apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-machines-deployment
  labels:
    app: processing-machines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-machines
  template:
    metadata:
      labels:
        app: processing-machines
    spec:
      containers:
      - name: processingmachines
        image: europe-west1-docker.pkg.dev/manufacturing-416112/images/processingmachines:latest
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ConnectionStrings__DatabaseConnectionString
            valueFrom:
              configMapKeyRef:
                name: sql-server-configmap
                key: processing-machines-connection-string
          - name: RabbitMqConfiguration__HostName
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: host-name