apiVersion: v1
kind: Service
metadata:
  name: transportations-service
spec:
  selector:
    app: transportations
  type: LoadBalancer
  ports:
    - name: transportations-service
      port: 5003
      targetPort: 80
      protocol: TCP
      nodePort: 30003
