apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: sql-server-storage-class