apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
  labels:
    app: sql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-server-secret
              key: sa-password
        volumeMounts:
        - name: sql-server-volume
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-server-volume
        persistentVolumeClaim:
          claimName: sql-server-volume