apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sql-server-storage-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard