apiVersion: apps/v1
kind: Deployment
metadata:
  name: materials-warehouse-deployment
  labels:
    app: materials-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: materials-warehouse
  template:
    metadata:
      labels:
        app: materials-warehouse
    spec:
      containers:
      - name: materialswarehouse
        image: europe-west1-docker.pkg.dev/manufacturing-416112/images/materialswarehouse:latest
        ports:
          - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: ConnectionStrings__DatabaseConnectionString
            valueFrom:
              configMapKeyRef:
                name: sql-server-configmap
                key: materials-warehouse-connection-string
          - name: RabbitMqConfiguration__HostName
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: host-name
