apiVersion: v1
kind: Service
metadata:
  name: materials-warehouse-service
spec:
  selector:
    app: materials-warehouse
  type: LoadBalancer
  ports:
    - name: materials-warehouse-service
      port: 5000
      targetPort: 80
      protocol: TCP
      nodePort: 30000
