apiVersion: v1
kind: Service
metadata:
  name: workflow-orchestrator-service
spec:
  selector:
    app: workflow-orchestrator
  type: LoadBalancer
  ports:
    - name: workflow-orchestrator-service
      port: 5004
      targetPort: 80
      protocol: TCP
      nodePort: 30004
