name: DeployRabbitMQ

on:
  workflow_dispatch:

env:
  DEPLOYMENT_FOLDER_PATH: deployment/gke/rabbitmq
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to google cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to the GKE cluster
      run: kubectl apply -f $DEPLOYMENT_FOLDER_PATH
