name: DeployMaterialsWarehouseService

on:
  workflow_dispatch:

env:
  IMAGE_NAME: materialswarehouse
  DOCKERFILE_PATH: MaterialsWarehouse/MaterialsWarehouse.API/Dockerfile
  DEPLOYMENT_FOLDER_PATH: deployment/gke/materials-warehouse
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to google cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Setup docker to authenticate
      run: gcloud auth configure-docker $CONTAINER_REGISTRY

    - name: Build docker image
      run: docker build . -f $DOCKERFILE_PATH -t $CONTAINER_REGISTRY/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest

    - name: Push docker image to container registry
      run: docker push $CONTAINER_REGISTRY/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest

    - name: Setup gke auth plugin
      uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - name: Deploy to the GKE cluster
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
        kubectl apply -f $DEPLOYMENT_FOLDER_PATH
