name: DeployTransportationsService

on:
  workflow_dispatch:

env:
  IMAGE_NAME: transportations
  DOCKERFILE_PATH: Transportations/Transportations.API/Dockerfile
  DEPLOYMENT_FOLDER_PATH: deployment/gke/transportations
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate to google cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Setup docker to authenticate
      run: gcloud auth configure-docker $CONTAINER_REGISTRY

    - name: Build docker image
      run: docker build . -f $DOCKERFILE_PATH -t $CONTAINER_REGISTRY/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest

    - name: Push docker image to container registry
      run: docker push $CONTAINER_REGISTRY/$PROJECT_ID/$REPOSITORY_NAME/$IMAGE_NAME:latest

    - name: Deploy to the GKE cluster
      run: kubectl apply -f $DEPLOYMENT_FOLDER_PATH
