name: WorkflowOrchestratorServiceDeploy

on:
  push:
    branches: [ "master" ]
    paths:
      - 'WorkflowOrchestrator/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'WorkflowOrchestrator/**'

env:
  PROJECT_PATH: "WorkflowOrchestrator/WorkflowOrchestrator.API/WorkflowOrchestrator.API.csproj"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_PATH }}
